name: baeit
description: noah-nomad baeit flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.7.0+801

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_messaging: ^11.2.6
  firebase_dynamic_links: ^3.0.1

  flutter_local_notifications: ^8.2.0

  http: ^0.13.4

  flutter_bloc: 7.0.1

  intl: ^0.17.0

  shared_preferences: ^2.0.13

  device_info_plus: ^2.1.0

  permission_handler: ^8.1.2

  geolocator: ^8.2.0

  fluttertoast: ^8.0.8

  animations: ^2.0.1

  path_provider: ^2.0.2

  sliding_up_panel: ^2.0.0+1

  syncfusion_flutter_sliders: ^19.2.47

  lottie: ^1.2.1

  dotted_border: ^2.0.0

  uuid: ^3.0.4

  image_picker: ^0.8.5

  multi_image_picker2: ^5.0.2

  flutter_staggered_grid_view: 0.4.0

  flutter_linkify: ^5.0.2

  url_launcher: ^6.0.9

  kakao_flutter_sdk: ^1.1.1

  sign_in_with_apple: ^3.2.0

  connectivity_plus: ^2.2.1

  image_cropper: ^1.4.1

  photo_view: ^0.12.0

  carousel_slider: ^4.0.0

  jwt_decoder: ^2.0.1

  flutter_datetime_picker: ^1.5.1

  rxdart: ^0.27.2

  package_info_plus: 1.0.6

  flutter_switch: ^0.3.2

  share_plus: ^3.0.4

  stomp_dart_client: ^0.4.4

  html: ^0.15.0

  flutter_widget_from_html_core: ^0.8.1

  notification_permissions: ^0.6.0

  file_picker: ^4.5.1

  flutter_keyboard_visibility: ^5.0.3

  filesize: ^2.0.1

  image_downloader: ^0.31.0

  open_file: ^3.2.1

  flutter_downloader: ^1.7.2

  amplitude_flutter: ^3.8.0

  webview_flutter: ^3.0.0

  channel_talk_flutter: ^2.2.0

  flutter_app_badger: ^1.3.0

  store_redirect: ^2.0.0

  airbridge_flutter_sdk: ^2.0.1

  facebook_app_events: ^0.14.8
#  flutter_facebook_sdk: ^1.0.0

  wrapped_korean_text: 0.0.2

  app_tracking_transparency: ^2.0.2+1

  uni_links: ^0.5.1

  flutter_uxcam: ^2.0.1

  downloads_path_provider_28: ^0.1.2

  firebase_remote_config: ^0.11.0+2

  flutter_image_compress: ^1.1.0

  naver_map_plugin:
    git: https://github.com/LBSTECH/naver_map_plugin.git

  shimmer: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^2.0.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "assets/images/public/app_icon.png"
  image_path_ios: "assets/images/public/app_icon_ios.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/public/app_icon_foreground.png"
  adaptive_icon_background: "#1CB78F"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/airbridge.json
    - assets/images/public/
    - assets/images/distance/
    - assets/images/navigation/
    - assets/images/neighborhood_class/
    - assets/images/detail/
    - assets/images/filter/
    - assets/images/select/
    - assets/images/create_class/
    - assets/images/request_class/
    - assets/images/my_page/
    - assets/images/notification/
    - assets/animations/
    - assets/images/test/

  fonts:
    - family: spoqahansansneo
      fonts:
        - asset: assets/fonts/spoqahansansneo_bold.otf
          weight: 700
        - asset: assets/fonts/spoqahansansneo_medium.otf
          weight: 500
        - asset: assets/fonts/spoqahansansneo_regular.otf
          weight: 400
        - asset: assets/fonts/spoqahansansneo_light.otf
          weight: 300
        - asset: assets/fonts/spoqahansansneo_thin.otf
          weight: 100